# Generated by Django 2.1 on 2019-09-12 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0009_auto_20190910_1547'),
        ('admins', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='admincomment',
            name='restaurant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='restaurant.Restaurant'),
            preserve_default=False,
        ),
    ]
