# Generated by Django 2.1 on 2019-08-21 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='soldOut',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='introduction',
            field=models.TextField(),
        ),
    ]
