# Generated by Django 2.1 on 2019-09-01 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0006_auto_20190827_0121'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantcategory',
            name='sequence',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
