# Generated by Django 2.1 on 2019-09-10 06:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('restaurant', '0008_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='follow',
            field=models.ManyToManyField(blank=True, related_name='follow', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='representative_menu',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurantcategory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='restaurant_category'),
        ),
    ]
