# Generated by Django 2.1 on 2019-09-17 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0010_auto_20190917_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='map_content',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurant',
            name='map_image',
            field=models.ImageField(blank=True, null=True, upload_to='map_image/'),
        ),
    ]
