# Generated by Django 2.1 on 2019-09-25 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0011_auto_20190917_1505'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurantcategory',
            old_name='image',
            new_name='image1',
        ),
        migrations.AddField(
            model_name='restaurantcategory',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='restaurant_category'),
        ),
        migrations.AddField(
            model_name='restaurantcategory',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='restaurant_category'),
        ),
    ]
