# Generated by Django 2.1 on 2019-09-25 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0012_auto_20190926_0050'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurantcategory',
            old_name='image1',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='restaurantcategory',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='restaurantcategory',
            name='image3',
        ),
    ]
