# Generated by Django 2.1 on 2019-10-01 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0016_auto_20191001_1255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dong',
            name='city',
        ),
        migrations.RemoveField(
            model_name='city',
            name='area',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='city',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='dong',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='detailArea',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Dong',
        ),
    ]
