# Generated by Django 2.1 on 2019-10-07 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0019_review_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='popular',
            field=models.BooleanField(default=False),
        ),
    ]
